name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    name: Run php tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up MySQL database
        uses: mirromutth/mysql-action@v1.1
        with:
          character set server: utf8mb4
          collation server: utf8mb4_unicode_520_ci
          mysql database: qbixxassignment_test
          mysql root password: qbixxassignment_test
          mysql user: qbixxassignment_test
          mysql password: qbixxassignment_test

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, imagick
          coverage: none

      - name: Check out code
        uses: actions/checkout@v2

      - name: Prepare the environment
        run: cp .env.testing .env

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Run tests
        run: php artisan test --parallel --order-by random
        env:
          DB_USERNAME: root
          DB_PASSWORD: qbixxassignment_test

  php-lint:
    name: Check PHP code style
    runs-on: ubuntu-latest
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, imagick
          coverage: none

      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare the environment
        run: cp .env.testing .env

      - name: Validate Composer configuration file
        run: composer validate

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader

      - name: Lint code
        run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
